name: Android Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Android App
        uses: PWABuilder/pwa-publish-action@v2
        with:
          android-key-store: ${{ secrets.ANDROID_KEYSTORE }}
